# build environment
FROM node:11 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
RUN yarn install --silent
RUN npm install gatsby-cli -g --silent

COPY . /usr/src/app
RUN gatsby build

# production environment
FROM nginx:alpine
RUN rm -rf /etc/nginx/conf.d
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the public folder
COPY --from=builder /usr/src/app/public /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]